### ISSUE TITLE
[PM] Session expiry functionality to be implemented

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#1224]
Once session get Expired (30 minutes Inactive), User should be logged out of the application and sign-in page should be displayed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by nagarjunav1** [comment]
Issue is still not fixed in latest DEV build

**Comment by sharathblr** [comment]
Hi @Kantharajut-btc find the expected behavior "


Scenario | EB | AB | Error message
-- | -- | -- | --
Admin/Super Admin session Timeout | User to be logged out when in idle state and navigated to sign in page and error message to be displayed in sign in page | User is logged out even when in idle state | EC_0080


Super Admin updates admin profile when logged in | User to be logged out and the error message should be displayed in Sign in screen | Not implemented | EC_0080
Parallel Login in different browser | User to be logged out in previously logged in browser and the error message to be displayed in sign in screen | User logged out in previously logged in the browser and the error message being  displayed in sign in screen | EC_0080
When superadmin update his own profile | NA | NA | NA

**Comment by nagarjunav1** [comment]
Closing this as it is tracked in other ticket #1557
