### ISSUE TITLE
[iOS] Occasionally getting 405 error on signout

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2876]
**Steps:**
1. Login
2. Navigate to my account
3. Change any settings in my account eg. change passcode/password/disable settings
4. Click on menu and signout
5. Observe

**Actual:** Occasionally getting 405 error on signout

**Expected:** User should not get any unexpected error 

Note: step 3 is not mandatory to reproduce the issue, issue is occasionally happening 

Refer video

https://user-images.githubusercontent.com/60386291/104805801-9ea43680-57f8-11eb-97e8-2fbbd9336bf5.MOV

**Comment by tushar-boston** [comment]
The error is intermittent and coming from the server.

**Comment by aswinijena100** [comment]
@tushar-boston please let me know which api returning 405 ?

**Comment by tushar-boston** [comment]
@aswinijena100 `/users/\(userID)/logout`

**Comment by harisboston** [comment]
405 - Method Not Allowed, is generic http response, when there is a mismatch between client and server side REST call, with invalid URI request.
Request from IOS:
```
case .logout(let userID):
      return Request(
        method: .post,
        path: "/users/\(userID)/logout",
        encoding: JSONEncoding.default
      )
```
Oauth server logout API:

```
@PostMapping(value = "/users/{userId}/logout", produces = MediaType.APPLICATION_JSON_VALUE)
  public ResponseEntity<UserResponse> logout(
      @PathVariable String userId,
      @RequestHeader(name = "Authorization") String token,
      HttpServletRequest request)
```
We will get 405 error, even if for any reason `{userId}` value is null in request.
@tushar-boston Kindly check or add if any validation is required for `userId` in the rest call.
Since this issue is not reproducible in Participant Manager and Android mobile app, and this issue is rarely found in IOS app. So keeping this issue under observation.

@nishit-v Kindly comment here when you encounter this issue again. Thanks.

**Comment by nishit-v** [comment]
Closing this ticket as issue is not reproducible in last iOS builds V1.0.170 and V1.0.169
