### ISSUE TITLE
[iOS] Studies list > Study status is not updated for 'Not Eligible' post withdrawing

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2921]
**Scenario 1:** Study status is not updated for 'Not Eligible' post withdrawing for open study

Steps:
1. Login and enroll into any open study successfully
2. Withdraw from the study
3. Again click on the withdrawn study
4. Fail the eligibility test
5. Observe the study status

**Scenario 2:** Study status is not updated for 'Not Eligible' post withdrawing for closed study having eligibility test

Steps:
1. Login and enroll into any closed study having eligibility test successfully
2. Withdraw from the study
3. PM admin enables and send the invitation again in the same site
4. From mobile click on the withdrawn study
5. Fail the eligibility test
6. Observe the study status

Actual: Study status is currently showing as 'WIthdrawn' 

Expected: Study status should be updated to 'Not Eligible' post withdrawing

**Comment by tushar-boston** [comment]
@aswinijena100 Even after updating the status to `notEligible`, the server returning `withdrawn`

<img width="417" alt="Screen Shot 2021-01-18 at 8 07 43 PM" src="https://user-images.githubusercontent.com/44088109/104928813-188b1a00-59c9-11eb-8c78-6e0bdf6cb6e9.png">

Also, I found another issue in the `studyState` service. We're getting the object of the old site of the same study. We should get the latest site information only if available, otherwise old.

<img width="409" alt="Screen Shot 2021-01-18 at 8 07 59 PM" src="https://user-images.githubusercontent.com/44088109/104928826-1c1ea100-59c9-11eb-8b31-6b50e8f5123d.png">

**Comment by sharathblr** [comment]
@Kantharajut-btc - Please provide details as to what is required?

**Comment by Kantharajut-btc** [comment]
Got clarification from nishit, thanks

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev

**Comment by Kantharajut-btc** [comment]
@nishit-v please close the issue
