### ISSUE TITLE
[SB] Usability issue - Part saving Study disables further editing 

### ISSUE THREAD

**Issue by hradhakrishnan** [GoogleCloudPlatform/fda-mystudies#3439]
Clicking "Save" part way through the Study Building process (e.g Study Information -> Save ), seems to disable the ability to further edit or modify other sections. 

When building complex studies ability to part-save and continue editing later would be expected behaviour from the end user. 

Steps to reproduce the behaviour:
1. Go to 'Study Builder'
2. Click on 'Create Study'
3. Enter information only on section  'Study Information'
4. Click "Save"
5. Rest of the study sections are greyed out from further editing (e.g Study settings, Overview etc...)

Expected behaviour
When building complex studies ability to part-save and continue editing later would be expected behaviour from the end user. Disabling other study sections during the study building process limits flexibility in study creation and forces the user to create a new study. 

**Screenshots**

Desktop (please complete the following information):
 - OS: [Chrome OS]
 - Browser [e.g. chrome]

**Comment by SR-btc** [comment]
Hi

Its only the first two sections (Study Information and Settings) that need to be 'marked complete' and not just 'saved',  in order to enable all the other sections, as these settings drive the content in other sections. Beyond that, all sections are open to concurrent editing and you can also save work in progress without other sections getting disabled.  

All sections have a Save button that lets you save work that is in progress. The 'mark complete' action also saves content but additionally validates for required content and then marks the section complete. The Actions section will allow you to publish your study once all sections are marked complete. 

For any section already marked complete, you can still go in and make updates/edits and again save or mark as completed, as needed. 

Also, the behavior of disabling other sections until the first two are marked complete, is only until the point the study is first launched or published. After this, all sections are open to concurrent editing ongoing, as the study's key identifiers and settings are already created and published for use by other platform components by that point and made non-editable thereafter, as indicated on the corresponding screen. Examples of fields that cannot be edited post-launch are Study ID, App ID etc. 

Hope this helps.

**Comment by hradhakrishnan** [comment]
@SR-btc Thanks that helped me proceed further with the study creation once i clicked "mark as complete".
