### ISSUE TITLE
[SB] Questionnaires/Active tasks > Anchor date based > Custom schedule > Error message is not displayed for 'X' value field

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3519]
Steps
1. Create/Edit study 
2. Navigate to Questionnaires/Active tasks 
3. Click on Add/Edit questionnaire
4. Enter all the required values in the Contents tab
5. Navigate to the Schedule tab
6. Select anchor date based and custom schedule
7. Don't enter any values in the Schedule tab
8. Click on the Done button
9. Observe 

AR: Error message is not getting displayed
ER: 'Please fill out this field' error message should be displayed

[**Note:** Issue should be fixed for both Questionnaires/Active task]

![error11](https://user-images.githubusercontent.com/71445210/116710791-c7d78400-a9ef-11eb-89d6-e6ca91347fdb.png)

**Comment by Lathan-btc** [comment]
@harisboston Issue still observed for the questionnaires in the following scenario
Questionnaires > Create a question with anchor date and custom > Click on edit questionnaire >Schedule tab > Switch to Regular > Add more than one run > Click on done button  and observe

AR: For the End time field error message is not getting displayed
ER: Error message should be displayed for the required fields when admin clicks on the done button without entering the mandatory fields

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance for the above scenarios

UI issues is observed for the below scenario
Questionnaires > Create a question with anchor date and custom > Click on edit questionnaire >Schedule tab > Add more than one run > Click on done button and observe

AR-There is no space between both the error message which is displayed for anchor date and time
ER-There should be a space between both the error message which is displayed for anchor date and time

[Note-Issue should be fixed for both questionnaire and active task]

![I_1](https://user-images.githubusercontent.com/86007179/126979391-cd3895e3-6e70-44f1-9db5-ed69dc9175ae.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by harisboston** [comment]
@bhoomikav16  issue is fixed in QA environment, kindly test and close this ticket.

**Comment by bhoomikav16** [comment]
Issue is fixed in the QA instance
