### ISSUE TITLE
Deployment read me update

### ISSUE THREAD

**Issue by mohangmk** [GoogleCloudPlatform/fda-mystudies#3575]
@moschetti 

As part of the recent XPN admin permission change (folder ->Org), we need to add the 6th step in the  "Create your devops project and configure CICD pipelines" deployment-Read Me section, since cloud build service account required organization level XPN admin permission, otherwise next step "Deploy your platform infrastructure" will fail due to lack of permission.

2 ways to handle above issue:
We need to capture organization ID as part of deployment.hcl and add the organization_Iam_member script to grant XPN admin role at organization level to cloud build service account under cicd folder->main.tf -This is going to be a major change.
As mentioned above, add the 6th point (capture the cloud build service account from the devops project and provide XPN admin permission at the organization level.)  -This is the simple way to handle the situation without disturbing the scripts.
Please let me know if you have any questions/ concerns.

**Comment by rpbaquing-stratusmeridian** [comment]
Based on my recent test of the deployment guide, the following should be included in the deployment readme:
1. Cloud Build api (cloudbuild.googleapis.com) should be enabled before the steps to generate the triggers for application configuration. The deployment terraform is able to create the triggers but the deployment will fail because the API is not enabled.
2. Firestore api (firestore.googleapis.com) should be enabled before creating the firestore instances and indexes in the firebase project.
