### ISSUE TITLE
[Android] Custom schedule > Upcoming > Custom schedule should show first run in the list

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3744]
1. Configure a custom schedule having multiple runs
2. Observe in Android mobile

Issue also observed in 'Past' section
Android:
![android](https://user-images.githubusercontent.com/60386291/121866226-58f28800-cd1c-11eb-8c92-7ca4dba9eac4.jpg)

iOS for reference:
![iOS](https://user-images.githubusercontent.com/60386291/121866257-61e35980-cd1c-11eb-9c91-5b2fc3ebd2f3.jpg)

**Comment by nishit-v** [comment]
Study Name: Activity Study
Activity Name: 3740_custom_regular

**Comment by nagarjunav1** [comment]
Issue still reproducible  in latest DEV build. Still highlighting the 2nd run instead of 1st run.

![image](https://user-images.githubusercontent.com/60500517/122080982-55462a80-ce1c-11eb-97af-2ac32dace26f.png)


![image](https://user-images.githubusercontent.com/60500517/122081088-6ee77200-ce1c-11eb-9aef-e8975bad6439.png)


Ref:- iOS screenshot

![image](https://user-images.githubusercontent.com/60500517/122081192-86265f80-ce1c-11eb-85b5-5da9554e4452.png)

**Comment by aswinijena100** [comment]
@nishit-v please check this issue

**Comment by nishit-v** [comment]
Issue is reproducible still for active task

![at](https://user-images.githubusercontent.com/60386291/122422205-98ce9f00-cfaa-11eb-82e9-a36a2f0fff2e.jpg)

![at1](https://user-images.githubusercontent.com/60386291/122422230-9d935300-cfaa-11eb-864c-0b209e54a176.jpg)

Study: FinalStudy

**Comment by nishit-v** [comment]
@harisboston `startTime` in outer object displating starttime of last run for active tasks custom schedule
Expected: Should show starttime of 1st run.


Issue observed only for active tasks custom schedule

![Screenshot_2](https://user-images.githubusercontent.com/60386291/122425377-11cef600-cfad-11eb-8239-bf6ab2555e05.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV build

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build

**Comment by harisboston** [comment]
@nishit-v Issue is fixed in QA instance, kindly test and update this ticket accordingly.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA
