### ISSUE TITLE
[PM] [IE browser] UI issue across the application

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4142]
**Steps:**

1. Open the IE browser.
2. Login to PM.
3. Observe all the screens and then Verify.

Note: Issue needs to be fixed across the application.

![Screenshot (259)](https://user-images.githubusercontent.com/86007179/134138002-56a53c65-2155-4dd7-90a6-2a09e1c3c6cd.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 
CSS variable it won't support in IE browser, it's outdated and overcome with an edge browser.

PM web app working fine in edge and other browsers, but IE library are not supporting.

Please note because of this IE11 is overcome with Edge browser. and i have sent mail pls check and close this ticket.

Google Chrome
CSS Variables (Custom Properties) are not compatible with Chrome browser 4 to 48. Chrome 49 to 67 partially supports this browser property.

Mozilla Firefox
CSS Variables (Custom Properties) are not supported for Firefox 2 to 30. Firefox 31 to 60 supports this browser.

Internet Explorer
IE browser version 6 to 11 doesn't support this browser element.

Safari
Safari browser 3.1 to 9 doesn't support this web element. Safari 9.1 to 11.1 supports this property.

Microsoft Edge
CSS Variables (Custom Properties) element is not supported by Microsoft Edge browser 12 to 14. Edge 15 partially supports this browser property. Later Edge version 16 and 17 support this browser element.

Opera
Opera browser 10.1 to 35 doesn't support this property. This property is supported for Opera 36 to 53.
![screencapture-caniuse-css-variables-2022-01-25-15_54_48](https://user-images.githubusercontent.com/59555917/150959250-1d8bc55e-3c34-4a54-b010-f18e5d4bdaf3.png)

**Comment by bhoomikav16** [comment]
UI issue is not observed in the latest edge and other browsers, So closing the ticket as per the above comment.
