### ISSUE TITLE
[GCI] [PM] Issue related to error message which is getting displayed for organizational users credentials in the sign in screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4414]
UI of Error message is getting displayed differently for organizational user credentials in the sign in screen
**AR:**
![Screenshot (202)](https://user-images.githubusercontent.com/86007179/152333107-9bd2bf8d-0e2b-4dda-9bfe-11596b8805c6.png)

**ER:** UI of Error message should get displayed similar for organizational user credentials in the sign in screen as similar to the non-organizational user
![qw](https://user-images.githubusercontent.com/86007179/152333681-a8f7c0f6-b41b-4434-b1fa-773518c22c13.png)

**Comment by harisboston** [comment]
- Above first image is error message which we are validating in client side where we do basic validation and show error below email and password. 
- Second image is alert message which we are validating in server side and show alert message.

- To address above issue, we will adjust the height of email/password box based on error message length. So that the error message will not cross the input box.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP branch in dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA instance
