### ISSUE TITLE
[iOS] Unable to enroll to the study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4584]
Participants are not able to enroll to the studies > Getting continuous loading after the consent flow

Note: Issue observed in the latest build 3.0(49)

App ID: GCPMOB001

**Comment by harisboston** [comment]
From logs
`2022-05-10 06:30:08.624 ERROR 1 --- [io-8080-exec-10] c.g.c.h.f.m.ConsentManagementAPIs        : Consent artifact creation failed with an exception

com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://healthcare.googleapis.com/v1/projects/btcsoft-dev-firebase/locations/us-east4/datasets/ConsentDataset/consentStores/iOSStudyP/consentArtifacts
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Permission healthcare.consentArtifacts.create denied on resource projects/btcsoft-dev-firebase/locations/us-east4/datasets/ConsentDataset/consentStores/iOSStudyP (or it may be malformed or not exist)",
    "reason" : "forbidden"
  } ],`

This issue is happening for old studies as consent logic and consent store is changed recently, so this issue should not happen for new studies. 
@Lathan-btc Please confirm.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
