### ISSUE TITLE
[IDP] [SB] [PM] Add admin > Email dropdown > Alignment issue with respect to 'Email text field and dropdown'

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4605]
**AR:** Alignment issue with respect to 'Email text field and dropdown' is observed in add admin screen, i.e., Length of dropdown and email text field is not aligned properly
**ER:** Alignment issue with respect to 'Email text field and dropdown' should be fixed in add admin screen, i.e., Alignment should be proper for length of dropdown and email text field

**Note:** Issue is not observed in 'Firefox' browser

![e](https://user-images.githubusercontent.com/86007179/170636225-49c1a5dc-af42-4f92-bf35-34eceac84379.png)

**Comment by Madhud5** [comment]
Hi @harisboston please implement this auto suggestion dropdown with select input dropdown itself. thank you

**Comment by akashkumarv3** [comment]
Hi, as per discussion with BA, Alignment is fixed but only in chrome, position is in right side because library is not supported in chrome's as per Madhu So we cannot update that, but alignment is fixed now.
UI will be as per the below screenshot attached.
![Screenshot (103)](https://user-images.githubusercontent.com/87967921/194322863-f4208428-fd5a-47b2-a9b1-560792d4cb5f.png)

**Comment by bhoomikav16** [comment]
As per the above comment by the dev team , Issue is fixed in the latest dev IDP QA instance
