### ISSUE TITLE
[Mobile apps] Getting an error message in the enrollment flow

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4662]
In enrollment flow,
**AR:** Getting an error message stating as " Sorry, an error has occurred and your request could not be processed. Please try again later. in the mobile apps
**ER:** Participants should be enrolled to the study without getting an error's

![f9836242-dcea-4d12-860b-fe8e644db062](https://user-images.githubusercontent.com/86007179/176670485-fae791c9-7b2b-4e31-90bb-ad9281ff6a25.jpg)

**Comment by harisboston** [comment]
This issue is happening for old studies not for new studies as dataset name in Healthcare is changed in dev env -- 
Dataset name: StudyId, Consent store name: CONSENT_StudyId.

Error: or it may be malformed or not exist, as  datastore name changed.

From Error logs: 

com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://healthcare.googleapis.com/v1/projects/btcsoft-dev-firebase/locations/us-east4/datasets/Standard/consentStores/CONSENT_Standard/consentArtifacts
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Permission healthcare.consentArtifacts.create denied on resource projects/btcsoft-dev-firebase/locations/us-east4/datasets/Standard/consentStores/CONSENT_Standard (or it may be malformed or not exist)",
    "reason" : "forbidden"
  } ],
  "message" : "Permission healthcare.consentArtifacts.create denied on resource projects/btcsoft-dev-firebase/locations/us-east4/datasets/Standard/consentStores/CONSENT_Standard (or it may be malformed or not exist)",
  "status" : "PERMISSION_DENIED"

**Comment by bhoomikav16** [comment]
As per the above comment , issue is not reproducing for new studies . So, Closing this issue
