### ISSUE TITLE
[iOS] [Offline indicator] Participant should stay in the same screen when user clicks on the 'Ok' button present on the below pop up once after participant's internet is back

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4835]
Steps:
1. Sign up or sign in to the app 
2. Click on any study
3. Click on a participate
4. Turn off the data
5. Click on Next button (an alert pop-up will get displayed)
6. Turn ON the Internet
7. Click on 'Ok' button present on the popup and observe

AR: Participant is navigating to the studies list screen 
ER: Participants should stay on the same screen and be able to complete the enrollment flow successfully

[Note: Issue should also be fixed in the Review updated consent flow]

![image](https://user-images.githubusercontent.com/71445210/185434844-dfc3a3fb-b80b-474d-a171-0133090654c3.png)

**Comment by amruthbtc** [comment]
@Lathan-btc  Enrolment flow is not suppose to work in offline, we are not saving the data locally, we are restricting the user at the entry point itself, There is a limitation in controlling the enrolment flow without internet, so we made a flow change when there is no internet, as during the enrolment flow, if we lost internet we have to exit from the enrolment process, if any further actions are proceeded without internet, because we may miss api calls. We have BA Confirmation for this alternative flow. So you can close it.

**Comment by Lathan-btc** [comment]
@amruthbtc As discussed with BA team please make the changes as follows

1. Offline > Click on Any button > Alert popup > Change the alert message to 'You may require internet connection to move forward with this flow. Kindly check the internet and try enrolling again.' with the 'Ok' button
2. Alert popup > On clicking on the 'Ok' button participant should navigate to the study overview screen

**Comment by amruthbtc** [comment]
issue fixed in 3.0.132

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
