### ISSUE TITLE
[iOS] [Offline indicator] There should be a consistency in offline error messages in both enrollment flow and review consent flow 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4837]
There should be a consistency in offline error messages in both enrollment flow and review consent flow 

**Enrollment flow:**

![image](https://user-images.githubusercontent.com/71445210/185437916-e61d5ba6-9f6f-4327-9c2d-82a06afd1c2b.png)

**Review updated consent:**

![image](https://user-images.githubusercontent.com/71445210/185438066-b47c5efe-5b84-457b-96b0-4f772ace9cc5.png)

**Comment by amruthbtc** [comment]
@Lathan-btc  Enrolment flow is not suppose to work in offline, we are not saving the data locally, we are restricting the user at the entry point itself, There is a limitation in controlling the enrolment flow without internet, so we made a flow change when there is no internet, as during the enrolment flow, if we lost internet we have to exit from the enrolment process, if any further actions are proceeded without internet, because we may miss api calls. We have BA Confirmation for this alternative flow. So you can close it.

**Comment by Lathan-btc** [comment]
@amruthbtc As discussed with the BA team please do the changes

**Comment by amruthbtc** [comment]
Issue fixed in 1.0.32 build

**Comment by Lathan-btc** [comment]
@amruthbtc 
1. When the user clicks on the Next button present on the Consent screen, the participant is navigating to the next screen when the participant is offline
2. Issue observed even in the First name last name screen
3. If the user is Offline then the user should get alert pop-up after clicking on the next button

[Note: Issue should be fixed in both enrollment and review update consent flow]

**Comment by amruthbtc** [comment]
@Lathan-btc we cannot restrict the user from a navigation at this scenario, what possible is, we can show the offline exit alert right after the "Next" button click.

**Comment by Lathan-btc** [comment]
Offline alert message is not getting displayed when the participant clicks on the 'Next' button

**Comment by Lathan-btc** [comment]
Issue will be tested once issue #4848 is fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
