### ISSUE TITLE
[deployment] add documentation to create a GCP workspace associated with the apps project

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#971]
A Workspace is required in order to monitor one or multiple projects.
https://cloud.google.com/monitoring/workspaces

**Comment by mohangmk** [comment]
@jkrogers18 .
As per our observation on the latest deployment, Monitoring work Space will be created automatically in any project, when you visit the cloud monitoring dashboard first time in that project.
Please let me know your thoughts.

**Comment by mohangmk** [comment]
@jkrogers18 
Details on setting up monitoring for a project:
The monitoring workspace needs to be created through the GCP console. There is no API support, as of now, to create it through Terraform

1. Instructions to create a monitoring workspace for the host project:
A GCP user with Monitoring Admin permissions needs to access the Monitoring Dashboard as a one time step to create the workspace for the selected  project (host project). The workspace is automatically created for that project, when the user accesses the Monitoring Dashboard for the first time.
https://cloud.google.com/monitoring/workspaces/create#single-project-workspace

2. Instructions to grant access to the project in the monitoring workspace:
    https://cloud.google.com/monitoring/workspaces/manage#sharing

3. Instructions to remove project from workspace:
 https://cloud.google.com/monitoring/workspaces/manage#remove-project

Please let us know if this information needs to be captured in the documentation or if you need any more information.

**Comment by mohangmk** [comment]
@moschetti 

I would like to follow up on above ticket. Please let us know whether above information need to be captured in the documentation or if you need any more information

**Comment by mohangmk** [comment]
@moschetti
We are closing this issue, as we have provided required details. Please feel free to reopen this ticket, if you need any more information.

**Comment by jaseva** [comment]
Hi @mohangmk, I am currently going through the semi-automated deployment process of release v2.0.11 and noticed errors in my gcp logs related to monitoring in my Apps and Data projects. I do not recall any manual steps indicated in the instructions for setting up a GCP workspace associated with the apps project. 

I currently am stuck trying to run the Android app and my configuration settings likely are the problem (unrelated to the monitoring resource errors produced), however you can view my error logs that contain the monitoring errors on this issue here:

https://github.com/GoogleCloudPlatform/fda-mystudies/issues/5123

The instructions above for maunually setting up monitoring on a project are outdated as the url links do not work. Can you point me in the right direction so I can resolve some of these errors? Thank you
